export const ACTION_CREATE_NAME_FOLDER = 'ACTION_CREATE_NAME_FOLDER';
export const ACTION_CREATE_NAME_NOTE = 'ACTION_CREATE_NAME_NOTE';
export const ACTION_CREATE_TEXT_NOTE = 'ACTION_CREATE_TEXT_NOTE';